// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: participate.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParticipateService_Participate_FullMethodName = "/proto.ParticipateService/Participate"
)

// ParticipateServiceClient is the client API for ParticipateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParticipateServiceClient interface {
	Participate(ctx context.Context, in *Thesis, opts ...grpc.CallOption) (*PartitipationResponse, error)
}

type participateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParticipateServiceClient(cc grpc.ClientConnInterface) ParticipateServiceClient {
	return &participateServiceClient{cc}
}

func (c *participateServiceClient) Participate(ctx context.Context, in *Thesis, opts ...grpc.CallOption) (*PartitipationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartitipationResponse)
	err := c.cc.Invoke(ctx, ParticipateService_Participate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParticipateServiceServer is the server API for ParticipateService service.
// All implementations must embed UnimplementedParticipateServiceServer
// for forward compatibility.
type ParticipateServiceServer interface {
	Participate(context.Context, *Thesis) (*PartitipationResponse, error)
	mustEmbedUnimplementedParticipateServiceServer()
}

// UnimplementedParticipateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParticipateServiceServer struct{}

func (UnimplementedParticipateServiceServer) Participate(context.Context, *Thesis) (*PartitipationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Participate not implemented")
}
func (UnimplementedParticipateServiceServer) mustEmbedUnimplementedParticipateServiceServer() {}
func (UnimplementedParticipateServiceServer) testEmbeddedByValue()                            {}

// UnsafeParticipateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParticipateServiceServer will
// result in compilation errors.
type UnsafeParticipateServiceServer interface {
	mustEmbedUnimplementedParticipateServiceServer()
}

func RegisterParticipateServiceServer(s grpc.ServiceRegistrar, srv ParticipateServiceServer) {
	// If the following call pancis, it indicates UnimplementedParticipateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParticipateService_ServiceDesc, srv)
}

func _ParticipateService_Participate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Thesis)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipateServiceServer).Participate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParticipateService_Participate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipateServiceServer).Participate(ctx, req.(*Thesis))
	}
	return interceptor(ctx, in, info, handler)
}

// ParticipateService_ServiceDesc is the grpc.ServiceDesc for ParticipateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParticipateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ParticipateService",
	HandlerType: (*ParticipateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Participate",
			Handler:    _ParticipateService_Participate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "participate.proto",
}
