// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.3
// source: participate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Thesis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThesisId    int32  `protobuf:"varint,1,opt,name=thesis_id,json=thesisId,proto3" json:"thesis_id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StudentId   string `protobuf:"bytes,4,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Token       string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Thesis) Reset() {
	*x = Thesis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_participate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Thesis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thesis) ProtoMessage() {}

func (x *Thesis) ProtoReflect() protoreflect.Message {
	mi := &file_participate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thesis.ProtoReflect.Descriptor instead.
func (*Thesis) Descriptor() ([]byte, []int) {
	return file_participate_proto_rawDescGZIP(), []int{0}
}

func (x *Thesis) GetThesisId() int32 {
	if x != nil {
		return x.ThesisId
	}
	return 0
}

func (x *Thesis) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Thesis) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Thesis) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Thesis) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type PartitipationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Approved bool `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
}

func (x *PartitipationResponse) Reset() {
	*x = PartitipationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_participate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartitipationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitipationResponse) ProtoMessage() {}

func (x *PartitipationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_participate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitipationResponse.ProtoReflect.Descriptor instead.
func (*PartitipationResponse) Descriptor() ([]byte, []int) {
	return file_participate_proto_rawDescGZIP(), []int{1}
}

func (x *PartitipationResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

var File_participate_proto protoreflect.FileDescriptor

var file_participate_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x06, 0x54,
	0x68, 0x65, 0x73, 0x69, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x68, 0x65, 0x73, 0x69, 0x73, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x68, 0x65, 0x73, 0x69, 0x73,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x33, 0x0a, 0x15, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x64, 0x32, 0x50, 0x0a, 0x12, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x68, 0x65, 0x73, 0x69, 0x73, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_participate_proto_rawDescOnce sync.Once
	file_participate_proto_rawDescData = file_participate_proto_rawDesc
)

func file_participate_proto_rawDescGZIP() []byte {
	file_participate_proto_rawDescOnce.Do(func() {
		file_participate_proto_rawDescData = protoimpl.X.CompressGZIP(file_participate_proto_rawDescData)
	})
	return file_participate_proto_rawDescData
}

var file_participate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_participate_proto_goTypes = []interface{}{
	(*Thesis)(nil),                // 0: proto.Thesis
	(*PartitipationResponse)(nil), // 1: proto.PartitipationResponse
}
var file_participate_proto_depIdxs = []int32{
	0, // 0: proto.ParticipateService.Participate:input_type -> proto.Thesis
	1, // 1: proto.ParticipateService.Participate:output_type -> proto.PartitipationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_participate_proto_init() }
func file_participate_proto_init() {
	if File_participate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_participate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Thesis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_participate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartitipationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_participate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_participate_proto_goTypes,
		DependencyIndexes: file_participate_proto_depIdxs,
		MessageInfos:      file_participate_proto_msgTypes,
	}.Build()
	File_participate_proto = out.File
	file_participate_proto_rawDesc = nil
	file_participate_proto_goTypes = nil
	file_participate_proto_depIdxs = nil
}
